### ISSUE TITLE
New Coffee Mocha Should Seed

### ISSUE THREAD

**Issue by padwasabimasala** [kata-seeds/kata-seed-template#3]
Hi, please forgive my dumbness but it wasn't quite clear from the instructions how you contribute new seeds.

Here's one for Coffee Mocha and Should

https://github.com/padwasabimasala/coffee-mocha-should-seed

Please let me know if you would prefer I contribute this by some other means

Best

**Comment by justincampbell** [comment]
Forked to https://github.com/kata-seeds/coffee-mocha-should-seed and added you to the JavaScript team. Thanks!

**Comment by padwasabimasala** [comment]
thank you

On Wed, May 6, 2015 at 6:24 PM, Justin Campbell notifications@github.com
wrote:

> Forked to https://github.com/kata-seeds/coffee-mocha-should-seed and
> added you to the JavaScript team. Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kata-seeds/kata-seed-template/issues/3#issuecomment-99656261
> .

## 

Matthew Thorley
